#!/usr/bin/env python3
"""AFFL Savant — ffopportunity expected-points downloader (resumable).

Downloads the ffverse/ffopportunity automated-release expected fantasy points
data (the exact payload nflreadr::load_ff_opportunity() serves). This is the
nflverse-canon expected-points model: completion probability (CP) + expected
YAC (xYAC) XGBoost models trained on nflfastR play-by-play, producing expected
stats per player-week that can be rescored to any league's scoring.

Assets land in data/raw/ffopportunity/ep_weekly_{y}.parquet, 2014-2025.

Release tag `latest-data` tracks the latest model version. The season file is
regenerated by ffverse automation; grain is player-week x position with
expected (exp) / actual / diff columns for pass/rush/rec stat families.
"""
import sys
import time
from pathlib import Path

import requests

RAW = Path(__file__).resolve().parent.parent / "data" / "raw" / "ffopportunity"
DL = "https://github.com/ffverse/ffopportunity/releases/download/latest-data"
YEARS = list(range(2014, 2026))


def download(name, tries=3):
    dest = RAW / name
    if dest.exists() and dest.stat().st_size > 1000:
        return "cached", dest.stat().st_size
    url = "%s/%s" % (DL, name)
    for attempt in range(tries):
        try:
            with requests.get(url, stream=True, timeout=300) as r:
                if r.status_code != 200:
                    if attempt < tries - 1:
                        time.sleep(2 * (attempt + 1))
                        continue
                    return "http %d" % r.status_code, 0
                tmp = dest.with_suffix(dest.suffix + ".tmp")
                with open(tmp, "wb") as f:
                    for chunk in r.iter_content(1 << 20):
                        f.write(chunk)
                tmp.rename(dest)
                return "ok", dest.stat().st_size
        except requests.RequestException as e:
            if attempt < tries - 1:
                time.sleep(2 * (attempt + 1))
                continue
            return "exc %s" % type(e).__name__, 0
    return "failed", 0


def main():
    RAW.mkdir(parents=True, exist_ok=True)
    failures = 0
    total = 0
    for y in YEARS:
        name = "ep_weekly_%d.parquet" % y
        status, size = download(name)
        total += size
        flag = "" if status in ("ok", "cached") else "  <-- FAIL"
        print("%-28s %-8s %8.1f MB%s" % (name, status, size / 1e6, flag))
        if flag:
            failures += 1
    print("total on disk: %.1f MB, failures: %d" % (total / 1e6, failures))
    sys.exit(1 if failures else 0)


if __name__ == "__main__":
    main()
